[features]
seeds = false

[programs.localnet]
gluex = "6ExBjE2VPbP8YZhWoXuBgSac5MHS3J8dfviUFuUeBqZe"

[programs.devnet]
gluex = "6ExBjE2VPbP8YZhWoXuBgSac5MHS3J8dfviUFuUeBqZe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/blake/.config/solana/id.json"

[scripts]
test = "yarn test"
